spring.application.name=em-project

server.port=9090

# Database setup
spring.datasource.url=jdbc:mysql://localhost:3306/osjlabs
spring.datasource.username=root
spring.datasource.password=Omkar@321
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate table creation
spring.jpa.hibernate.ddl-auto=update

# Show SQL
spring.jpa.show-sql=true